### PR TITLE
Make Schema Registry URL optional

### LINKED ISSUE #186: Cleanup job fails if topic doesn't have associated schema
The [word-count example pipeline](https://github.com/bakdata/kpops-examples/blob/main/word-count/deployment/kpops/pipeline.yaml) doesn't use topic schemas. When running the streams-app-cleanup-job it fails with
```
com.bakdata.kafka.CleanUpException: Could not reset schema registry for topic word-count-app-word-counter-topic-KSTREAM-AGGREGATE-STATE-STORE-0000000003-repartition
    at com.bakdata.kafka.util.SchemaTopicClient.resetSchemaRegistry(SchemaTopicClient.java:118)
    at java.base/java.util.ArrayList.forEach(Unknown Source)
    at com.bakdata.kafka.CleanUpRunner.run(CleanUpRunner.java:158)
    at com.bakdata.kafka.KafkaStreamsApplication.cleanUpRun(KafkaStreamsApplication.java:334)
    at com.bakdata.kafka.KafkaStreamsApplication.runCleanUp(KafkaStreamsApplication.java:328)
    at com.bakdata.kafka.KafkaStreamsApplication.run(KafkaStreamsApplication.java:121)
    at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
    at picocli.CommandLine.access$1500(CommandLine.java:148)
    at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
    at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
    at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
    at picocli.CommandLine.execute(CommandLine.java:2170)
    at com.bakdata.kafka.KafkaApplication.startApplicationWithoutExit(KafkaApplication.java:127)
    at com.bakdata.kafka.KafkaApplication.startApplication(KafkaApplication.java:101)
    at com.bakdata.kpops.examples.WordCountApplication.main(WordCountApplication.java:18)
Caused by: java.net.MalformedURLException: no protocol: /subjects
    at java.base/java.net.URL.<init>(Unknown Source)
    at java.base/java.net.URL.<init>(Unknown Source)
    at java.base/java.net.URL.<init>(Unknown Source)
    at io.confluent.kafka.schemaregistry.client.rest.RestService.url(RestService.java:1310)
    at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:279)
    at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:384)
    at io.confluent.kafka.schemaregistry.client.rest.RestService.getAllSubjects(RestService.java:1037)
    at io.confluent.kafka.schemaregistry.client.rest.RestService.getAllSubjects(RestService.java:1022)
    at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getAllSubjects(CachedSchemaRegistryClient.java:677)
    at com.bakdata.kafka.util.SchemaTopicClient.resetSchemaRegistry(SchemaTopicClient.java:102)
    ... 16 more
```

### PR DESCRIPTION
**Pull request by raminqaf**
Fixes #186

### CODE REVIEW

File: src/main/java/com/bakdata/kafka/KafkaApplication.java [hunk 1]
```diff
@@ -80,8 +74,8 @@ public abstract class KafkaApplication implements Runnable {
                     + "consumer group. Be careful with running in production and with enabling this flag - it "
                     + "might cause inconsistent processing with multiple replicas.")
     protected boolean cleanUp;
-    @CommandLine.Option(names = "--schema-registry-url", required = true, description = "URL of schema registry")
-    private String schemaRegistryUrl = "";
+    @CommandLine.Option(names = "--schema-registry-url", description = "URL of schema registry")
+    private Optional<String> schemaRegistryUrl;
```
Comment (philipp94831) [inline src/main/java/com/bakdata/kafka/KafkaApplication.java:84]: Using optionals for fields is bad practice

File: src/main/java/com/bakdata/kafka/KafkaApplication.java [hunk 2]
```diff
@@ -80,8 +80,8 @@ public abstract class KafkaApplication implements Runnable {
                     + "consumer group. Be careful with running in production and with enabling this flag - it "
                     + "might cause inconsistent processing with multiple replicas.")
     protected boolean cleanUp;
-    @CommandLine.Option(names = "--schema-registry-url", required = true, description = "URL of schema registry")
-    private String schemaRegistryUrl = "";
+    @CommandLine.Option(names = "--schema-registry-url", description = "URL of schema registry")
```
Comment (disrupted) [inline src/main/java/com/bakdata/kafka/KafkaApplication.java:83]: check capitalization of Schema Registry

**Review by disrupted — CHANGES_REQUESTED** [review]

File: src/main/java/com/bakdata/kafka/KafkaProducerApplication.java [hunk 3]
```diff
@@ -38,6 +37,8 @@
 import org.apache.kafka.clients.producer.ProducerConfig;
 import org.jooq.lambda.Seq;
 
+import java.util.Properties;
```
Comment (philipp94831) [inline src/main/java/com/bakdata/kafka/KafkaProducerApplication.java:40]: Is that the correct code style?

File: src/test/java/com/bakdata/kafka/integration/StreamsCleanUpTest.java [hunk 4]
```diff
@@ -25,48 +25,16 @@
...
-import com.bakdata.kafka.CloseFlagApp;
-import com.bakdata.kafka.KafkaStreamsApplication;
-import com.bakdata.kafka.TestRecord;
-import com.bakdata.kafka.test_applications.ComplexTopologyApplication;
-import com.bakdata.kafka.test_applications.MirrorKeyWithAvro;
-import com.bakdata.kafka.test_applications.MirrorValueWithAvro;
-import com.bakdata.kafka.test_applications.WordCount;
-import com.bakdata.kafka.test_applications.WordCountPattern;
+import com.bakdata.kafka.*;
+import com.bakdata.kafka.test_applications.*;
```
Comment (philipp94831) [inline src/test/java/com/bakdata/kafka/integration/StreamsCleanUpTest.java]: Fix code style

**Review by philipp94831 — CHANGES_REQUESTED** [review]

File: src/main/java/com/bakdata/kafka/KafkaApplication.java (hunk 1 above)
Comment (raminqaf) [reply src/main/java/com/bakdata/kafka/KafkaApplication.java:84]: But this is supported in [PicoCLI](https://picocli.info/#_optionalt). Should I consider a default `null` value instead?

File: azure-pipelines.yml [hunk 5]
```diff
@@ -19,6 +19,7 @@ resources:
     - repository: templates
       type: github
       name: bakdata/bakdata-project-templates
+      ref: tmp/upload-snapshot
```
Comment (raminqaf) [inline azure-pipelines.yml:22]: TODO: Remove after testing is finished

File: src/main/java/com/bakdata/kafka/KafkaApplication.java (hunk 1 above)
Comment (philipp94831) [reply src/main/java/com/bakdata/kafka/KafkaApplication.java:84]: Just a plain String field. Will be null by default anyways. Just because PicoCLI supports it, it is still bad practice because Optional is not Serializable for example. IntelliJ will warn you as well

File: src/main/java/com/bakdata/kafka/KafkaStreamsApplication.java [hunk 6]
```diff
@@ -319,11 +320,11 @@ protected StateListener getStateListener() {
     protected void runCleanUp() {
         try (final ImprovedAdminClient adminClient = this.createAdminClient()) {
             final CleanUpRunner cleanUpRunner = CleanUpRunner.builder()
```
Comment (philipp94831) [inline src/main/java/com/bakdata/kafka/KafkaStreamsApplication.java:322]: @raminqaf I guess you never fixed the root cause of the issue because you need to check in the clean up runner if SR url is configured and then clean schemas or not https://github.com/bakdata/streams-bootstrap/blob/master/src/main/java/com/bakdata/kafka/util/ImprovedAdminClient.java#L60

File: charts/producer-app/README.md [hunk 7]
```diff
@@ -36,26 +36,26 @@ Alternatively, a YAML file that specifies the values for the parameters can be p
...
-| `streams.config`            | Configurations for your [Kafka producer app](https://kafka.apache.org/documentation/#producerconfigs).     | `{}`    |
-| `streams.outputTopic`       | Output topic for your producer application.                                                                |         |
-| `streams.extraOutputTopics` | Map of additional named output topics if you need to specify multiple topics with different message types. | `{}`    |
+| Parameter                   | Description                                                                                                | Default          |
+| --------------------------- | ---------------------------------------------------------------------------------------------------------- | ---------------- |
+| `streams.brokers`           | Comma separated list of Kafka brokers to connect to.                                                       |                  |
+| `streams.schemaRegistryUrl` | URL of schema registry to connect to.                                                                      | Optional.empty() |
```
Comment (disrupted) [inline charts/producer-app/README.md:50]: nit: capitalization is wrong here as well

File: src/main/java/com/bakdata/kafka/KafkaProducerApplication.java [hunk 8]
```diff
@@ -85,17 +89,21 @@ public void run() {
...
         // exactly once and order
         kafkaConfig.put(ProducerConfig.MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION, 1);
         kafkaConfig.setProperty(ProducerConfig.ACKS_CONFIG, "all");
 
         // compression
         kafkaConfig.setProperty(ProducerConfig.COMPRESSION_TYPE_CONFIG, "gzip");
 
-        this.getSchemaRegistryUrl()
-            .map(srUrl -> kafkaConfig.setProperty(AbstractKafkaSchemaSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG, srUrl));
+        if (nonNull(this.getSchemaRegistryUrl())) {
```
Comment (philipp94831) [inline src/main/java/com/bakdata/kafka/KafkaProducerApplication.java:101]: set the String serializer in the else

File: src/main/java/com/bakdata/kafka/KafkaStreamsApplication.java [hunk 9]
```diff
@@ -269,10 +271,13 @@ protected Properties createKafkaProperties() {
 
         // topology
         kafkaConfig.put(StreamsConfig.APPLICATION_ID_CONFIG, this.getUniqueAppId());
-        kafkaConfig.put(StreamsConfig.DEFAULT_KEY_SERDE_CLASS_CONFIG, SpecificAvroSerde.class);
-        kafkaConfig.put(StreamsConfig.DEFAULT_VALUE_SERDE_CLASS_CONFIG, SpecificAvroSerde.class);
-        this.getSchemaRegistryUrl()
-            .map(srUrl -> kafkaConfig.setProperty(AbstractKafkaSchemaSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG, srUrl));
+
+        if (nonNull(this.getSchemaRegistryUrl())) {
```
Comment (philipp94831) [inline src/main/java/com/bakdata/kafka/KafkaStreamsApplication.java:275]: see above

File: src/main/java/com/bakdata/kafka/util/ImprovedAdminClient.java [hunk 10]
```diff
@@ -44,25 +45,26 @@ public final class ImprovedAdminClient implements Closeable {
 
     @Getter
     private final @NonNull Properties properties;
-    @Getter
     private final @NonNull AdminClient adminClient;
-    @Getter
-    private final @NonNull SchemaRegistryClient schemaRegistryClient;
+    private final String schemaRegistryUrl;
```
Comment (philipp94831) [inline src/main/java/com/bakdata/kafka/util/ImprovedAdminClient.java:49]: Use schemaRegistryClient as field but make it nullable

File: src/test/java/com/bakdata/kafka/CleanUpRunnerTest.java [hunk 11]
```diff
@@ -41,7 +40,7 @@ class CleanUpRunnerTest {
     void createTemporaryPropertiesFile() throws IOException {
         final WordCount wordCount = new WordCount();
         wordCount.setInputTopics(List.of("input"));
-        wordCount.setSchemaRegistryUrl(Optional.empty());
+        wordCount.setSchemaRegistryUrl(null);
```
Comment (philipp94831) [inline src/test/java/com/bakdata/kafka/CleanUpRunnerTest.java:43]: No need to set it to null

**Review by philipp94831 — CHANGES_REQUESTED** [review]

File: src/main/java/com/bakdata/kafka/KafkaApplication.java [hunk 12]
```diff
@@ -178,8 +178,8 @@ public ImprovedAdminClient createAdminClient() {
         final ImprovedAdminClient.ImprovedAdminClientBuilder adminClientBuilder = ImprovedAdminClient.builder()
             .properties(this.getKafkaProperties())
             .timeout(ADMIN_TIMEOUT);
-        if (nonNull(this.getSchemaRegistryUrl())) {
-            adminClientBuilder.schemaRegistryUrl(this.getSchemaRegistryUrl());
+        if (nonNull(this.schemaRegistryUrl)) {
```
Comment (philipp94831) [inline src/main/java/com/bakdata/kafka/KafkaApplication.java:181]: Why even have the if? you can also pass null to the builder method, so just always pass `this.schemaRegistryUrl`

File: src/main/java/com/bakdata/kafka/util/ImprovedAdminClient.java [hunk 13]
```diff
@@ -56,13 +57,14 @@ private ImprovedAdminClient(@NonNull final Properties properties,
...
-        this.schemaRegistryUrl = schemaRegistryUrl;
+        this.schemaRegistryClient =
+            schemaRegistryUrl == null ? null : createSchemaRegistryClient(this.properties, schemaRegistryUrl);
         this.timeout = timeout;
     }
 
     public Optional<SchemaClient> getSchemaClient() {
-        if (nonNull(this.schemaRegistryUrl)) {
-            return Optional.of(new SchemaClient(createSchemaRegistryClient(this.properties, this.schemaRegistryUrl)));
+        if (nonNull(this.schemaRegistryClient)) {
```
Comment (philipp94831) [inline src/main/java/com/bakdata/kafka/util/ImprovedAdminClient.java:66]: `return Optional.ofNullable(this.schemaRegistryClient).map(SchemaClient::new)`

File: src/test/java/com/bakdata/kafka/CliTest.java [hunk 14]
```diff
@@ -286,7 +286,7 @@ public void run() {
                 .containsEntry("role1", List.of("input3"))
                 .containsEntry("role2", List.of("input4", "input5"));
         assertThat(app.getInputTopics("role1")).isEqualTo(List.of("input3"));
-        assertThat(app.getInputTopic("role2")).isEqualTo("input4");
+        assertThat(app.getInputTopics("role2")).contains("input4");
```
Comment (philipp94831) [inline src/test/java/com/bakdata/kafka/CliTest.java:289]: Please focus on the changes of the PR and don't fix stuff all over the place. Feel free to submit a clean up PR

**Review by philipp94831 — CHANGES_REQUESTED** [review]

File: src/main/java/com/bakdata/kafka/util/ImprovedAdminClient.java (hunk 13 above)
Comment (raminqaf) [reply src/main/java/com/bakdata/kafka/util/ImprovedAdminClient.java:66]: Damn 🤯

File: src/main/java/com/bakdata/kafka/CleanUpRunner.java [hunk 15]
```diff
@@ -188,20 +188,24 @@ public void run(final boolean deleteOutputTopic) {
...
     }
 
     private void runTopicCleanUp(final String topic) {
         this.topicCleanUpHooks.forEach(hook -> hook.accept(topic));
     }
 
-    private void deleteTopic(final String topic) {
-        this.adminClient.getSchemaTopicClient().deleteTopicAndResetSchemaRegistry(topic);
+    private void deleteTopicAndResetSchema(final String topic) {
+        this.adminClient.getTopicClient()
```
Comment (philipp94831) [inline src/main/java/com/bakdata/kafka/CleanUpRunner.java:205]: I think it is cleaner to leave this logic in the SchemaTopicClient. Or have two different implementations of the same interface. One SchemaTopicClient which does both and one TopicClient that only acts on topics

File: src/main/java/com/bakdata/kafka/KafkaProducerApplication.java [hunk 16]
```diff
@@ -69,7 +74,9 @@ public void run() {
 
     /**
      * <p>This method should give a default configuration to run your producer application with.</p>
-     * To add a custom configuration please add a similar method to your custom application class:
+     * If the {@link KafkaApplication#schemaRegistryUrl} is set the {@link SpecificAvroSerializer} is set as the default
```
Comment (philipp94831) [inline src/main/java/com/bakdata/kafka/KafkaProducerApplication.java:77]:
```suggestion
     * If {@link KafkaApplication#schemaRegistryUrl} is set, {@link SpecificAvroSerializer} is set as the default
```

File: src/main/java/com/bakdata/kafka/KafkaProducerApplication.java [hunk 17]
```diff
@@ -85,20 +92,29 @@ public void run() {
...
         kafkaConfig.setProperty(ProducerConfig.COMPRESSION_TYPE_CONFIG, "gzip");
 
-        kafkaConfig.setProperty(AbstractKafkaSchemaSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG, this.getSchemaRegistryUrl());
+        this.configureDefaultSerializer(kafkaConfig);
         kafkaConfig.setProperty(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, this.brokers);
         return kafkaConfig;
     }
 
+    private void configureDefaultSerializer(final Properties kafkaConfig) {
+        if (nonNull(this.schemaRegistryUrl)) {
```
Comment (philipp94831) [inline src/main/java/com/bakdata/kafka/KafkaProducerApplication.java:108]: why not just `this.schemaRegistryUrl == null`? (caution, I inverted the condition)

File: src/main/java/com/bakdata/kafka/KafkaProducerApplication.java [hunk 18]
```diff
@@ -126,8 +145,15 @@ protected void cleanUpRun(final SchemaTopicClient schemaTopicClient) {
         }
     }
 
+    private static void deleteTopicAndResetSchema(final TopicClient topicClient,
```
Comment (philipp94831) [inline src/main/java/com/bakdata/kafka/KafkaProducerApplication.java:148]: Do not duplicate code here. Beforehand it was nice and reusable. Probably related to my comment above

File: src/main/java/com/bakdata/kafka/KafkaStreamsApplication.java [hunk 19]
```diff
@@ -79,19 +82,19 @@ public abstract class KafkaStreamsApplication extends KafkaApplication implement
     @CommandLine.Option(names = "--error-topic", description = "Error topic")
     protected String errorTopic;
     @CommandLine.Option(names = "--extra-input-topics", split = ",", description = "Additional named input topics",
-            converter = {UseDefaultConverter.class, StringListConverter.class})
+        converter = {UseDefaultConverter.class, StringListConverter.class})
```
Comment (philipp94831) [inline src/main/java/com/bakdata/kafka/KafkaStreamsApplication.java:85]: I just used downloaded our code style and the indent does not change so I think you misconfigured sth

File: src/main/java/com/bakdata/kafka/util/ImprovedAdminClient.java [hunk 20]
```diff
@@ -44,25 +45,25 @@ public final class ImprovedAdminClient implements Closeable {
...
     private final @NonNull AdminClient adminClient;
-    @Getter
-    private final @NonNull SchemaRegistryClient schemaRegistryClient;
     private final @NonNull Duration timeout;
+    private final SchemaRegistryClient schemaRegistryClient;
 
     @Builder
     private ImprovedAdminClient(@NonNull final Properties properties,
-            @NonNull final String schemaRegistryUrl, @NonNull final Duration timeout) {
+        @NonNull final Duration timeout, final String schemaRegistryUrl) {
```
Comment (philipp94831) [inline src/main/java/com/bakdata/kafka/util/ImprovedAdminClient.java:54]: why?

File: src/test/java/com/bakdata/kafka/integration/RunProducerAppTest.java [hunk 21]
```diff
@@ -93,33 +93,31 @@ protected Properties createKafkaProperties() {
         app.setBrokers(this.kafkaCluster.getBrokerList());
         app.setSchemaRegistryUrl(this.schemaRegistryMockExtension.getUrl());
         app.setOutputTopic(output);
-        app.setStreamsConfig(Map.of(
-                ConsumerConfig.SESSION_TIMEOUT_MS_CONFIG, "10000"
-        ));
+        app.setStreamsConfig(Map.of(ConsumerConfig.SESSION_TIMEOUT_MS_CONFIG, "10000"));
```
Comment (philipp94831) [inline src/test/java/com/bakdata/kafka/integration/RunProducerAppTest.java:96]: why? multi lines behave nicer when changed in git diff

**Review by philipp94831 — CHANGES_REQUESTED** [review]
Check Sonar https://sonarcloud.io/summary/new_code?id=com.bakdata.kafka%3Astreams-bootstrap

File: src/main/java/com/bakdata/kafka/CleanUpRunner.java [hunk 22]
```diff
@@ -201,7 +202,8 @@ private void runTopicCleanUp(final String topic) {
     }
 
     private void deleteTopic(final String topic) {
-        this.adminClient.getSchemaTopicClient().deleteTopicAndResetSchemaRegistry(topic);
+        this.adminClient.getSchemaTopicClient()
```
Comment (philipp94831) [inline src/main/java/com/bakdata/kafka/CleanUpRunner.java:205]: A schematopic client has to always be there, no?

File: src/main/java/com/bakdata/kafka/KafkaProducerApplication.java [hunk 23]
```diff
@@ -110,14 +110,19 @@ protected <K, V> KafkaProducer<K, V> createProducer() {
      */
     protected void runCleanUp() {
         try (final ImprovedAdminClient improvedAdminClient = this.createAdminClient()) {
-            this.cleanUpRun(improvedAdminClient.getSchemaTopicClient());
+            this.cleanUpRun(improvedAdminClient);
         }
     }
 
-    protected void cleanUpRun(final SchemaTopicClient schemaTopicClient) {
+    protected void cleanUpRun(final ImprovedAdminClient improvedAdminClient) {
```
Comment (philipp94831) [inline src/main/java/com/bakdata/kafka/KafkaProducerApplication.java:117]: Just leave it as it was before and handle the presence of schema registry in SchemaTopicClient

**Review by philipp94831 — CHANGES_REQUESTED** [review]

File: src/main/java/com/bakdata/kafka/util/ImprovedAdminClient.java [hunk 24]
```diff
@@ -44,20 +44,19 @@ public final class ImprovedAdminClient implements Closeable {
 
     @Getter
     private final @NonNull Properties properties;
-    @Getter
```
Comment (philipp94831) [inline src/main/java/com/bakdata/kafka/util/ImprovedAdminClient.java:47]: Why did you remove this?

File: src/main/java/com/bakdata/kafka/util/ImprovedAdminClient.java [hunk 25]
```diff
@@ -44,20 +44,19 @@ public final class ImprovedAdminClient implements Closeable {
...
     private final @NonNull AdminClient adminClient;
-    @Getter
```
Comment (philipp94831) [inline src/main/java/com/bakdata/kafka/util/ImprovedAdminClient.java:49]: Why did you remove this? We should keep the getter but make it return an optional

File: src/main/java/com/bakdata/kafka/util/SchemaTopicClient.java [hunk 26]
```diff
@@ -97,7 +109,11 @@ public void deleteTopicAndResetSchemaRegistry(final String topic) {
      * @param topic the topic name
      */
     public void resetSchemaRegistry(final String topic) {
-        log.info("Resetting schema registry for topic '{}'", topic);
+        if (this.schemaRegistryClient == null) {
+            log.info("No Schema Registry URL set. Skipping schema deletion for topic {}.", topic);
```
Comment (philipp94831) [inline src/main/java/com/bakdata/kafka/util/SchemaTopicClient.java:113]: I think debug is fine

File: src/test/java/com/bakdata/kafka/util/SchemaTopicClientTest.java [hunk 27]
```diff
@@ -47,64 +48,129 @@
...
+        this.softly.assertThat(client.getAllSubjects())
+                .contains(TOPIC + "-value");
+
+        try (final SchemaTopicClient schemaTopicClient = this.createClientWithSchemaRegistry()) {
+            schemaTopicClient.resetSchemaRegistry(TOPIC);
+        }
+
+        delay(TIMEOUT_SECONDS, TimeUnit.SECONDS);
+
+        this.softly.assertThat(client.getAllSubjects())
```
Comment (philipp94831) [inline src/test/java/com/bakdata/kafka/util/SchemaTopicClientTest.java:138]: Isn't that the same test as above?

**Review by philipp94831 — CHANGES_REQUESTED** [review]

File: src/main/java/com/bakdata/kafka/util/ImprovedAdminClient.java (hunk 25 above)
Comment (raminqaf) [reply src/main/java/com/bakdata/kafka/util/ImprovedAdminClient.java:49]: Good idea I'll add a getter

File: src/test/java/com/bakdata/kafka/util/SchemaTopicClientTest.java (hunk 27 above)
Comment (raminqaf) [reply src/test/java/com/bakdata/kafka/util/SchemaTopicClientTest.java:138]: One is testing `deleteTopicAndResetSchemaRegistry` method and the other one this `resetSchemaRegistry`. I improved the naming of the methods and the test assertion

**Comment by philipp94831** [comment]
Please go ahead and test it

File: src/test/java/com/bakdata/kafka/PropertiesTest.java [hunk 28]
```diff
@@ -36,19 +44,83 @@ class PropertiesTest {
...
-                        "--streams-config", "kafka=streams"});
+                        "--streams-config", "kafka=streams"
+                });
         assertThat(app.getKafkaProperties())
                 .containsEntry("foo", "baz")
                 .containsEntry("kafka", "streams")
                 .containsEntry("hello", "world");
     }
 
+    @Test
```
Comment (torbsto) [inline src/test/java/com/bakdata/kafka/PropertiesTest.java:62]: Could you also include the schema registry url property in the added tests?

File: src/test/java/com/bakdata/kafka/test_applications/WordCount.java [hunk 29]
```diff
@@ -57,19 +52,12 @@ public void buildTopology(final StreamsBuilder builder) {
                 .groupBy((key, word) -> word)
                 .count(Materialized.as("counts"));
 
-        wordCounts.toStream().to(this.outputTopic, Produced.with(stringSerde, longSerde));
+        final Serde<Long> longValueSerde = Serdes.Long();
+        wordCounts.toStream().to(this.outputTopic, Produced.valueSerde(longValueSerde));
```
Comment (torbsto) [inline src/test/java/com/bakdata/kafka/test_applications/WordCount.java:56]: Could be inlined 
```suggestion
        wordCounts.toStream().to(this.outputTopic, Produced.valueSerde(Serdes.Long()));
```

File: src/test/java/com/bakdata/kafka/util/SchemaTopicClientTest.java [hunk 30]
```diff
@@ -47,64 +47,142 @@
...
                 .doesNotContain(TOPIC + "-value");
+        this.softly.assertThat(this.kafkaCluster.exists(TOPIC))
+                .isTrue();
+    }
+
+    @Test
+    void shouldDeleteTopicAndKeepSchemaWhenSchemaRegistryUrlIsNotSet() throws InterruptedException, RestClientException,
```
Comment (torbsto) [inline src/test/java/com/bakdata/kafka/util/SchemaTopicClientTest.java:145]: This currently results in a failure and I think we should try to keep it that way, because I'd argue this is always an oversight and a misconfiguration

Comment (torbsto) [reply src/test/java/com/bakdata/kafka/util/SchemaTopicClientTest.java:145]: Maybe we can check if any serializer or deserializer is an instance of AbstractKafkaSchemaSerDe and then require the SR url to be set?

Comment (philipp94831) [reply src/test/java/com/bakdata/kafka/util/SchemaTopicClientTest.java:145]: What is resulting in a failure? Tests are passing, no?

Comment (torbsto) [reply src/test/java/com/bakdata/kafka/util/SchemaTopicClientTest.java:145]: By currently I mean the current version of stream-bootstrap without the changes of this PR. I think `shouldDeleteTopicAndKeepSchemaWhenSchemaRegistryUrlIsNotSet` is not a behavior we ever want

Comment (philipp94831) [reply src/test/java/com/bakdata/kafka/util/SchemaTopicClientTest.java:145]: But that is what this PR is about. Clean was failing because SR was not configured (or rather was configured but there was no endpoint to call). That's why we changed clean up behavior and only call SR if it is configured. Otherwise it will be logged: https://github.com/bakdata/streams-bootstrap/pull/187/files#diff-7b49d6ef833e64cf10ebb2f829f2444c33a61923e58889c9d34c0a2cb4fc64a8R113. Because you usually call clean with the same values as deploy, SR should be configured consistently

Comment (philipp94831) [reply src/test/java/com/bakdata/kafka/util/SchemaTopicClientTest.java:145]: I mean in this case the user also wouldn't be able to deploy because SR is not configured and the AvroSerde does not work. So I think it is fine. Also is there a way to check all configured Serdes in Kafka Streams?

Comment (raminqaf) [reply src/test/java/com/bakdata/kafka/util/SchemaTopicClientTest.java:145]: @philipp94831 maybe something like this could work:
```java
    public final Properties getKafkaProperties() {
        final Properties kafkaConfig = this.createKafkaProperties();

        EnvironmentStreamsConfigParser.parseVariables(System.getenv())
                .forEach(kafkaConfig::setProperty);
        this.streamsConfig.forEach(kafkaConfig::setProperty);

        final StreamsConfig config = new StreamsConfig(kafkaConfig);

        if ((config.defaultValueSerde() instanceof SpecificAvroSerde
                || config.defaultKeySerde() instanceof SpecificAvroSerde) && this.schemaRegistryUrl == null) {
            System.out.println("Oh! Bad config! Watch out!");
        }

        return kafkaConfig;
    }
```

Comment (philipp94831) [reply src/test/java/com/bakdata/kafka/util/SchemaTopicClientTest.java:145]: You can still manually set serdes for Stores/Topics/...

Comment (raminqaf) [reply src/test/java/com/bakdata/kafka/util/SchemaTopicClientTest.java:145]: I can remove this test if it is ambiguous.

Comment (torbsto) [reply src/test/java/com/bakdata/kafka/util/SchemaTopicClientTest.java:145]: I've looked into it and it seems to me there is no way for us to get Serdes from a topology.

File: azure-pipelines.yml (hunk 5 above)
Comment (philipp94831) [reply azure-pipelines.yml:22]: @raminqaf Please revert and I will approve

**Review by philipp94831 — APPROVED** [review]
